# Common aliases

alias rebash="pushd ~ && . .bashrc && popd"
alias sshlpc="ssh -tY cmslpc25.fnal.gov"
alias sshhep="ssh -tY hep"
alias uwl="kinit -k -t ~/private/kelong.keytab kelong@CERN.CH && ssh -Y kelong@uwlogin"
#alias uwlh="kinit -k -t ~/private/kelong.keytab kelong@CERN.CH && ssh kelong@lxplus712.cern.ch -t ssh uwlogin"
alias uwlh="ssh kelong@lxplus716.cern.ch -t ssh uwlogin"
#Use uwli (initialize), then make a new tab and run uwlx (x11) for x11 forwarding
alias uwli="ssh kelong@lxplus.cern.ch -L 8888:uwlogin.cern.ch:22"
alias uwlx="ssh kelong@localhost -p 8888 -X"
alias ll6="ssh -Y kdlong@login06.hep.wisc.edu"
alias ll1="ssh -Y kdlong@login01.hep.wisc.edu"
alias lxp="kinit -k -t ~/private/kelong.keytab && ssh kelong@lxplus.cern.ch"
alias lxp016="kinit -k -t ~/private/kelong.keytab && ssh kelong@lxplus016.cern.ch"
alias csctunnel="ssh -C -t -L 1080:localhost:4321 kelong@lxplus.cern.ch ssh -C -D 4321 kelong@cmsusr"
alias csctunnelcern="ssh -C -t -L 1080:localhost:4321 kelong@cmsusr"
alias cq="condor_q $USER"
alias vi=vim
alias setupcrab="source /cvmfs/cms.cern.ch/crab3/crab.sh"
alias sshuw="ssh -tY uwlogin 'echo \$DISPLAY > ~/.Xdisplay && tmux attach'"
alias kk="kinit -k -t ~/private/kelong.keytab kelong@CERN.CH && aklog"
alias updatePermissions="while sleep 3600; do echo 'Refreshing AFS'; date +%Y%m%d%H%M%S; kk; done"
alias hdfsls="hdfs dfs -ls"
alias hdfsrm="hdfs dfs -rm"
alias k5tmux="/usr/bin/k5reauth -f -p kelong -k ~/private/kelong.keytab -- tmux"
#alias k5tmux="k5reauth -f -i 600 -p kelong -k ~/private/kelong.keytab -- tmux"
